import json
from textwrap import dedent

from app.config import get_settings
from app.schemas import AIRequest, AIResult


MODE_LABELS = {
    "generate": "AI Code Generator",
    "debug": "Bug Finder and Debugger",
    "explain": "Code Explanation",
    "optimize": "Code Optimizer",
    "refactor": "Code Refactoring",
    "convert": "Code Converter",
    "test": "Test Case Generator",
    "document": "Documentation Generator",
    "chat": "AI Chat",
}


class AIProvider:
    def __init__(self):
        self.settings = get_settings()

    def analyze(self, payload: AIRequest) -> AIResult:
        if not self.settings.demo_mode and self.settings.openai_api_key:
            return self._call_openai(payload)
        return self._demo_response(payload)

    def _call_openai(self, payload: AIRequest) -> AIResult:
        from openai import OpenAI

        client = OpenAI(api_key=self.settings.openai_api_key)
        response = client.chat.completions.create(
            model=self.settings.openai_model,
            temperature=0.2,
            response_format={"type": "json_object"},
            messages=[
                {
                    "role": "system",
                    "content": dedent(
                        """
                        You are a careful AI coding assistant. Return only valid JSON with these keys:
                        result, explanation, generated_code, corrected_code, issues_found,
                        suggested_improvements, time_complexity, space_complexity, test_cases,
                        documentation.

                        Never claim that user-submitted code was executed. Do not run code. If code
                        is risky, explain the risk and suggest safe alternatives.
                        """
                    ).strip(),
                },
                {"role": "user", "content": self._build_prompt(payload)},
            ],
        )
        content = response.choices[0].message.content or "{}"
        try:
            data = json.loads(content)
        except json.JSONDecodeError:
            data = {"result": content, "explanation": "The model returned plain text instead of JSON."}
        return self._normalize_result(data)

    def _build_prompt(self, payload: AIRequest) -> str:
        target = f"\nTarget language: {payload.target_language}" if payload.target_language else ""
        return dedent(
            f"""
            Mode: {MODE_LABELS.get(payload.mode, payload.mode)}
            Programming language: {payload.language}{target}

            User request:
            {payload.instruction or "No additional instruction provided."}

            User code:
            ```{payload.language}
            {payload.code or "No code provided."}
            ```

            Provide concise, practical help suitable for a developer. For debugging, identify
            the error, explain the cause, provide corrected code, edge cases, and tests. For
            generation, return clean executable code and a short explanation.
            """
        ).strip()

    def _normalize_result(self, data: dict) -> AIResult:
        list_fields = ["issues_found", "suggested_improvements", "test_cases"]
        normalized = {}
        for key in AIResult.model_fields:
            value = data.get(key, "" if key not in list_fields else [])
            if key in list_fields and isinstance(value, str):
                value = [line.strip("- ").strip() for line in value.splitlines() if line.strip()]
            normalized[key] = value
        return AIResult(**normalized)

    def _demo_response(self, payload: AIRequest) -> AIResult:
        language = payload.language or "Python"
        mode = MODE_LABELS.get(payload.mode, "AI Assistant")
        generated_code = self._sample_code(language, payload)

        issue = "No runtime execution was performed. Review the suggestions before using them."
        if payload.mode == "debug":
            issue = "Potential logic, boundary, or syntax issues were checked from static context only."
        elif payload.mode == "convert":
            issue = f"Conversion target is {payload.target_language or 'not selected'}."

        return AIResult(
            result=f"{mode} completed in demo mode.",
            explanation=(
                "This structured demo response is generated by the backend because no OPENAI_API_KEY "
                "is configured. Add a key in backend/.env to receive live model output."
            ),
            generated_code=generated_code if payload.mode in {"generate", "convert", "test", "document"} else "",
            corrected_code=generated_code if payload.mode in {"debug", "optimize", "refactor"} else "",
            issues_found=[issue],
            suggested_improvements=[
                "Keep functions small and name variables by intent.",
                "Validate edge cases before integrating the code.",
                "Add unit tests for normal, boundary, and invalid inputs.",
            ],
            time_complexity="O(n) for the sample algorithm.",
            space_complexity="O(1) extra space for the sample algorithm.",
            test_cases=[
                "Input: [4, 1, 9, 2] -> Expected: 9",
                "Input: [] -> Expected: handled as empty input",
                "Input with duplicates -> Expected: stable, documented behavior",
            ],
            documentation=(
                "Configure OPENAI_API_KEY to generate documentation tailored to the submitted code."
            ),
        )

    def _sample_code(self, language: str, payload: AIRequest) -> str:
        lower = language.lower()
        if "java" in lower and "script" not in lower:
            return dedent(
                """
                import java.util.Arrays;

                public class SecondLargest {
                    public static int findSecondLargest(int[] nums) {
                        if (nums == null || nums.length < 2) {
                            throw new IllegalArgumentException("Array must contain at least two numbers.");
                        }

                        int largest = Integer.MIN_VALUE;
                        int secondLargest = Integer.MIN_VALUE;

                        for (int num : nums) {
                            if (num > largest) {
                                secondLargest = largest;
                                largest = num;
                            } else if (num > secondLargest && num != largest) {
                                secondLargest = num;
                            }
                        }

                        if (secondLargest == Integer.MIN_VALUE) {
                            throw new IllegalArgumentException("Array must contain at least two distinct numbers.");
                        }
                        return secondLargest;
                    }

                    public static void main(String[] args) {
                        int[] nums = {10, 4, 7, 10, 2};
                        System.out.println(findSecondLargest(nums));
                    }
                }
                """
            ).strip()
        if "javascript" in lower or lower in {"js", "typescript"}:
            return dedent(
                """
                export function findSecondLargest(values) {
                  const unique = [...new Set(values)];
                  if (unique.length < 2) {
                    throw new Error("At least two distinct values are required.");
                  }
                  unique.sort((a, b) => b - a);
                  return unique[1];
                }
                """
            ).strip()
        if "c++" in lower or "cpp" in lower:
            return dedent(
                """
                #include <algorithm>
                #include <iostream>
                #include <stdexcept>
                #include <vector>

                int findSecondLargest(const std::vector<int>& nums) {
                    if (nums.size() < 2) {
                        throw std::invalid_argument("At least two values are required.");
                    }
                    int largest = nums[0];
                    int second = nums[1];
                    if (second > largest) std::swap(largest, second);

                    for (size_t i = 2; i < nums.size(); ++i) {
                        if (nums[i] > largest) {
                            second = largest;
                            largest = nums[i];
                        } else if (nums[i] > second && nums[i] != largest) {
                            second = nums[i];
                        }
                    }
                    return second;
                }
                """
            ).strip()
        if lower == "c":
            return dedent(
                """
                int max_value(const int values[], int length) {
                    int best = values[0];
                    for (int i = 1; i < length; i++) {
                        if (values[i] > best) {
                            best = values[i];
                        }
                    }
                    return best;
                }
                """
            ).strip()
        return dedent(
            """
            def find_second_largest(values: list[int]) -> int:
                unique_values = sorted(set(values), reverse=True)
                if len(unique_values) < 2:
                    raise ValueError("At least two distinct values are required.")
                return unique_values[1]


            if __name__ == "__main__":
                print(find_second_largest([10, 4, 7, 10, 2]))
            """
        ).strip()
